name: Mirror master to KennyVos/my-repo-mirror

on:
  push:
    branches:
      - master

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Mirror master to my-repo-mirror
      env:
        PAT: ${{ secrets.MIRROR_PAT }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        # Voeg mirror remote toe met PAT-authenticatie
        git remote add mirror "https://x-access-token:${PAT}@github.com/KennyVos/my-repo-mirror.git"

        # Push enkel de master branch
        git push mirror master --force
